excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://paulmarrington.github.io
title: Paul Marrington
tagline: On Programming Languages
description: I have always had an interest in programming languages. My latest effort is Lispz for the browser.
paginate: 5
