excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://paulmarrington.github.io
title: Paul Marrington
tagline: On Programming Languages
description: I have always had an interest in programming languages. I implemented RatFOR to make FORTRAN more palatable in the late 70's and FORTH on new hardware a few years later. I have developed 4 or 5 languages since, culminating in Lispz for the browser.
paginate: 5